### ISSUE TITLE
"master" vs "develop" branches

### ISSUE THREAD

**Issue by alyst** [BioJulia/BioAlignments.jl#49]
What is the status of these branches?
Right now PRs are merged into "master", but e.g. `docs/make.jl` are still configured to treat *"develop"* as development branch, and the docs/readme mention *"develop"* as the development branch.

I think it should be configured to be consistent with the rest of *BioJulia*, the ambiguous branch should be removed, and docs updated.

**Comment by jakobnissen** [comment]
Right. The BioJulia contribution guidelines state that [the dedicated maintainer chooses the git branching model](https://github.com/BioJulia/Contributing/blob/master/CONTRIBUTING.md#a-suggested-branching-model).

Since both Ben Ward and Kenta Sato have been inactive, I guess the dedicated maintainer is me.

Let's have the OneFlow model - developments are merged into master, and we have only the master branch, temporary feature/bugfix branches, and perhaps occasionally one for an upcoming release.
